controllers CinemaHallController, OrderController, UserController, Sh…
IrynaDim/Movie-Shop pull request #10
Opened 2020-10-26 15:34 UTC by IrynaDim

…oppingCartController were created

2020-10-26 18:00 UTC, aleksandr-hrankin commented on src/main/java/com/dev/cinema/controllers/OrderController.java
> +    public void complete(@RequestBody OrderRequestDto orderDto) {
А зачем нам здесь OrderRequestDto если из него мы используем только userId)

2020-10-26 18:00 UTC, aleksandr-hrankin commented on src/main/java/com/dev/cinema/controllers/OrderController.java
> +    @GetMapping("/get-order")
Плохое название для url

2020-10-26 18:00 UTC, aleksandr-hrankin commented on src/main/java/com/dev/cinema/controllers/ShoppingCartController.java
> +    @GetMapping("/get")
the same

2020-10-26 18:00 UTC, aleksandr-hrankin commented on src/main/java/com/dev/cinema/controllers/UserController.java
> +@RequestMapping("/user")
```suggestion
@RequestMapping("/users")
```

2020-10-26 19:36 UTC, IrynaDim commented on src/main/java/com/dev/cinema/controllers/OrderController.java
> +    public void complete(@RequestBody OrderRequestDto orderDto) {
не знаю, но на QA сказали в OrderRequestDto оставить только id. поэтому пока не удаляю.

2020-10-27 09:03 UTC, KseniiaMakarova requested changes

2020-10-27 09:03 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/controllers/CinemaHallController.java
> +@RequestMapping("/cinema-hall")
```suggestion
@RequestMapping("/cinema-halls")
```
let's change this to plural everywhere

2020-10-27 09:03 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/controllers/OrderController.java
> +    public void complete(@RequestBody OrderRequestDto orderDto) {
на данном этапе можно userId передать любым способом

2020-10-27 09:03 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/controllers/OrderController.java
> +    @GetMapping("/get-order")
I agree - see task description

2020-10-27 09:03 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/controllers/OrderController.java
> +    public List<OrderResponseDto> getOrderById(@RequestParam Long userId) {
```suggestion
    public List<OrderResponseDto> getOrderHistoryOfUser(@RequestParam Long userId) {
```

2020-10-27 09:03 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/controllers/OrderController.java
> +        List<Ticket> ticket = cart.getTickets();
```suggestion
        List<Ticket> tickets = cart.getTickets();
```
be attentive with the naming

2020-10-27 09:03 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/controllers/ShoppingCartController.java
> +@RequestMapping("/cart")
see task description

2020-10-27 09:03 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/controllers/ShoppingCartController.java
> +    @GetMapping("/get")
same

2020-10-27 09:03 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/controllers/mapper/CinemaHallMapper.java
> +package com.dev.cinema.controllers.mapper;
move all your mappers to `service/mappers` folder

2020-10-27 09:03 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/dto/OrderResponseDto.java
> +    private List<Long> ticketsId;
```suggestion
    private List<Long> ticketIds;
```

2020-10-27 09:03 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/dto/ShoppingCartResponseDto.java
> +    private Long userId;
aren't id and userId the same?

2020-10-27 09:03 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/dto/UserResponseDto.java
> +    private String password;
let's not disclose secure data

2020-10-27 10:26 UTC, IrynaDim commented on src/main/java/com/dev/cinema/controllers/OrderController.java
> +    public void complete(@RequestBody OrderRequestDto orderDto) {
done

2020-10-27 10:27 UTC, IrynaDim commented on src/main/java/com/dev/cinema/controllers/OrderController.java
> +    @GetMapping("/get-order")
done

2020-10-27 10:28 UTC, IrynaDim commented on src/main/java/com/dev/cinema/controllers/ShoppingCartController.java
> +    @GetMapping("/get")
done

2020-10-27 10:28 UTC, IrynaDim commented on src/main/java/com/dev/cinema/controllers/UserController.java
> +@RequestMapping("/user")
done

2020-10-27 10:29 UTC, IrynaDim commented on src/main/java/com/dev/cinema/controllers/OrderController.java
> +    public List<OrderResponseDto> getOrderById(@RequestParam Long userId) {
done

2020-10-27 10:30 UTC, IrynaDim commented on src/main/java/com/dev/cinema/controllers/OrderController.java
> +        List<Ticket> ticket = cart.getTickets();
done

2020-10-27 10:31 UTC, IrynaDim commented on src/main/java/com/dev/cinema/controllers/ShoppingCartController.java
> +@RequestMapping("/cart")
done

2020-10-27 10:31 UTC, IrynaDim commented on src/main/java/com/dev/cinema/controllers/ShoppingCartController.java
> +    @GetMapping("/get")
done

2020-10-27 10:33 UTC, IrynaDim commented on src/main/java/com/dev/cinema/model/dto/OrderResponseDto.java
> +    private List<Long> ticketsId;
done

2020-10-27 10:36 UTC, IrynaDim commented on src/main/java/com/dev/cinema/model/dto/ShoppingCartResponseDto.java
> +    private Long userId;
done

2020-10-27 10:36 UTC, IrynaDim commented on src/main/java/com/dev/cinema/model/dto/UserResponseDto.java
> +    private String password;
done

2020-10-27 10:37 UTC, IrynaDim commented on src/main/java/com/dev/cinema/controllers/mapper/CinemaHallMapper.java
> +package com.dev.cinema.controllers.mapper;
done

2020-10-27 12:37 UTC, KseniiaMakarova approved these changes
good job!

2020-10-27 12:47 UTC, merged