solution was added
IrynaDim/Movie-Shop pull request #7
Opened 2020-10-15 13:59 UTC by IrynaDim

2020-10-15 18:49 UTC, vladkuzya approved these changes
Nice work!

2020-10-15 20:06 UTC, KseniiaMakarova requested changes

2020-10-15 20:06 UTC, KseniiaMakarova commented on pom.xml
> +        </dependency>
why so many dependencies? log4j would be enough

2020-10-15 20:06 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/Main.java
> +import java.util.logging.Logger;
wrong class imported in all the projects

also, you are missing `log4j.properties` configuration file

2020-10-15 20:06 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/Main.java
> +    private static Logger logger = Logger.getLogger(Main.class.getName());
you should be possible to pass class, not a string, after you import the right Logger class

2020-10-15 20:06 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/Main.java
> +        logger.info("Get order by user id: " + orderService.getOrderHistory(iryna));
let's wrap call to `login()` method in try-catch and add log.warn with the informative message in `catch` block

2020-10-15 20:06 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/dao/impl/CinemaHallDaoImpl.java
> +    private static Logger logger = Logger.getLogger(CinemaHallDao.class.getName());
```suggestion
    private static final Logger logger = Logger.getLogger(CinemaHallDaoImpl.class);
```
same everywhere

2020-10-16 07:17 UTC, KseniiaMakarova requested changes

2020-10-16 07:17 UTC, KseniiaMakarova commented on pom.xml
> +        </dependency>
do you use this dependency?

2020-10-16 07:17 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/Main.java
> +    private static Logger logger = Logger.getLogger(Main.class);
```suggestion
    private static final Injector injector = Injector.getInstance("com.dev.cinema");
    private static final Logger logger = Logger.getLogger(Main.class);
```

2020-10-16 07:17 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/Main.java
> +        logger.info("Get order by user id: " + orderService.getOrderHistory(iryna));
reconsider these messages, I think they are confusing

2020-10-16 07:17 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/dao/impl/CinemaHallDaoImpl.java
> +    private static final Logger logger = Logger.getLogger(CinemaHallDao.class);
```suggestion
    private static final Logger logger = Logger.getLogger(CinemaHallDaoImpl.class);
```
fix this in all the classes

2020-10-16 08:16 UTC, KseniiaMakarova approved these changes

2020-10-16 08:58 UTC, merged